export const ADD_TO_DISPLAY = 'ADD_TO_DISPLAY';
export const REMOVE_FROM_DISPLAY = 'REMOVE_FROM_DISPLAY';

export const ADD_TO_SCHDULE = 'ADD_TO_SCHDULE';
export const REMOVE_FROM_SCHDULE = 'REMOVE_FROM_SCHDULE';
